language: c
sudo: false
notifications:
  email: false

script: make

branches:
  only:
  - master

addons:
  apt:
    packages: &common_deps
    - pkg-config
    - libfuse-dev
    - curl
    - libjansson-dev

matrix:
  include:
  - compiler: gcc-5
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-5
        - *common_deps
  - compiler: gcc-6
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-6
        - *common_deps
  - compiler: gcc-7
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-7
        - *common_deps
  - compiler: clang-3.9
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-3.9
        packages:
        - clang-3.9
        - *common_deps
  - compiler: clang-4.0
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-4.0
        packages:
        - clang-4.0
        - *common_deps
  - compiler: clang-5.0
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty
        packages:
        - clang-5.0
        - *common_deps

before_install:
- eval "${MATRIX_EVAL}"
