---
name: "Mac build"

"on":
  push:
    branches:
      - feature/gh-actions-mac
      - release/*

jobs:
  build:
    runs-on: macos-11.0
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Make python virtual env
        run: python3 -m venv .env

      - name: Build binary
        run: make build-quick
